### ISSUE TITLE
Compatibility with R 4.0.0

### ISSUE THREAD

**Issue by marklhc** [sfcheung/semptools#43]
Since [R 4.0.0](https://cran.r-project.org/doc/manuals/r-release/NEWS.html) was out, I tested whether the package can be installed with the newest version of R. So far it can be installed without issues, and runs fine with all vignettes built successfully. I'll continue to run a few tests on it.

**Comment by sfcheung** [comment]
Thanks. It's time to migrate to R 4.x.x. R 4.0.1 was just released and I will do future development on this version in addition to R 3.6.3.

**Comment by sfcheung** [comment]
I close this issue because we are now using R 4.1.x and so all changes to be made will automatically take this version into account.
