### ISSUE TITLE
Write some tests using testthat

### ISSUE THREAD

**Issue by sfcheung** [sfcheung/semptools#48]
The generated output is a qgraph object. Therefore, it is possible to write some tests for the functions to see if the changes to a qgraph is the intended ones.

**Comment by marklhc** [comment]
I've added some unit tests related to #45, as in 94c5000 and 7258954.

**Comment by sfcheung** [comment]
Thanks! @marklhc ! Your tests can serve as templates for other functions. Let's close this issue for now and write tests as the needs arise.
