### ISSUE TITLE
Add or drop nodes from a semPlotModel object

### ISSUE THREAD

**Issue by sfcheung** [sfcheung/semptools#56]
This should be done before using semPaths. Functions have been drafted and being tested in the experimental branch `experimental_sf`.

Done in the nodes_keep_drop branch. Tested. (1e1f80fa5344811d04aed295ab02ec535aa49231, 1984249aba3be1341cd5329b35ecae7d3665dc4c)

**Comment by marklhc** [comment]
Not sure whether it's relevant, but `semPlot::semPaths()` accepts the argument `structural = TRUE` which only shows the structural model and drops the measurement indicators. I tested that with a few functions in `semptools` and I think it works fine.

**Comment by sfcheung** [comment]
Thanks, @marklhc. I added this because of a real case. We have a lot of control variables which we want to omit from a diagram (they will be included in the table of estimates). Therefore, that function does not work for us.

I already drafted them in an experimental branch (experimental_sf), intended for testing (and using) those functions in that project. You can take a look.

**Comment by sfcheung** [comment]
With those two functions, users can drop or keep any nodes they want (in principle). This can be quite useful when there are a lot of control variables, or when users when to present a subset of a model for readability.
