### ISSUE TITLE
Write a function to specify the curve attributes of selected edges

### ISSUE THREAD

**Issue by sfcheung** [sfcheung/semptools#6]
This can be done manually using `​​curve`. The goal is to make this task user friendly, and users can specify only edges that they want to change.

Do this in its own branch.

**Comment by pa0** [comment]
Is my bug or `set_curve` not setting the curvature for covariate edges? It happened when I used `layout = m` when m is a hand-made matrix.

```
m <- matrix(c(NA,"sms",NA,
              "Eks",NA,"tap",
              "Smn",NA,"taf"), 3, 3, byrow=T)

semPaths(
  model_test.fit,
  what = "std",  whatLabels = "std",
  edge.label.cex = 1.15,
  layout = m,
  sizeMan = 5,
  residuals = F,
  edge.color = "black",   fade = F,  esize = 1,       
  DoNotPlot = T
) |>
  mark_sig(model_test.fit, alpha = c(" " = 1.00, "*" = .01)) |>
  set_curve(curve_list = c("Eks ~~ Smn" = 3, "tap ~ sms" = 3)) |>
  plot()
```

`tap ~ sms` is beautifully curved, but `Eks ~~ Smn` sadly not

<img width="490" alt="image" src="https://user-images.githubusercontent.com/4692217/199978336-a063c81e-b0c9-4c64-8c78-fa8f6d20b969.png">

**Comment by sfcheung** [comment]
@pa0 , thanks for reporting this issue.

This reveals a bug of `set_curve()`. There is a quick workaround for now. Just change `"Eks ~~ Smn"` to `"Smn ~~ Eks"`.

I have thought about cases like this one and added code to handle them. However, somehow the function still failed to work in your case. I will fix this issue later.

Thanks again.

**Comment by pa0** [comment]
Thanks, the workaround is working!
BTW: some of the edges need plus, and some need minus to achieve curvature in the same direction.

`my_curve_list <- c(
  "taf ~~ tap" = 2.6,
  "sap ~~ tap" = 2.8,
  "saf ~~ tap" = 3,
  "oaf ~~ tap" = 3.2,
  "oap ~~ tap" = 3.4,
  
  "sap ~~ taf" = 2.6,
  "saf ~~ taf" = 2.8,
  "oaf ~~ taf" = 3,
  "oap ~~ taf" = 3.2,
  
  "saf ~~ sap" = 2.6,
  "oaf ~~ sap" = 2.8,
  "oap ~~ sap" = 3,
  
  "oaf ~~ saf" = 2.6,
  "oap ~~ saf" = 2.8,
  
  "oaf ~~ oap" = -2.6,  # here is the minus sign
  
  "Ugd ~~ Eks" = -2.8,
  "Smn ~~ Eks" = -3.0,
  "St_ ~~ Eks" = -3.2,
  "Int ~~ Eks" = -3.4,
  
  "Smn ~~ Ugd" = -2.8,
  "St_ ~~ Ugd" = -3.0,
  "Int ~~ Ugd" = -3.2,

  "St_ ~~ Smn" = -2.8,
  "Int ~~ Smn" = -3.0,
  
  "Int ~~ St_" = -2.8
)`

<img width="669" alt="image" src="https://user-images.githubusercontent.com/4692217/201525128-690821ab-2557-43da-b082-7bdd0bafcedb.png">

**Comment by sfcheung** [comment]
The effect of the sign (+ or -) depends on which node (variable) is on the left hand side of the formula (`~~`). This may sound strange because the arrow is double-headed and so where the arrow starts should not matter. However, internally, it does have a start and an end, and this affects the interpretation of the sign.

For now, the solution is trial-and-error, not a nice one. I will see if there is a user-friendly solution.
