### ISSUE TITLE
Test not passed on my machine (Ubuntu 20.04) due to `all.equal()` returns strings with curly double quotes

### ISSUE THREAD

**Issue by marklhc** [sfcheung/semptools#62]
The build did not pass the test "Curve and edge label position can be changed after changing labels" on my Ubuntu machine. It seems that on @sfcheung's machine, the return value of 
```r
all.equal(p_pa2$graphAttributes$Edges, 
                      p_pa2_curve$graphAttributes$Edges)
```
is 

```
Component \"curve\": Mean absolute difference: 1
```

but on my machine, the return value is 

```
Component “curve”: Mean absolute difference: 1
```
(with curly double quotes). 

I'll soon push a quick fix by replacing all curly double quotes to `\"` before passing the values to `expect_match()`, so that it should work on both machines

**Comment by sfcheung** [comment]
@marklhc , thanks! I am not aware of this difference. I will see if I can build a linux box (or a VM) later. I close this issue because  881c3de has been merged into the `devel` branch.
